# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='uri',
            field=models.URLField(null=True),
        ),
    ]
