# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0002_annotation_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ranges',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='uri',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
