# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0003_auto_20170624_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
