# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 17:17
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_auto_20170625_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='permissions',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
