# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_auto_20170830_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='body',
            new_name='html_text',
        ),
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AddField(
            model_name='document',
            name='is_in_category',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='document',
            name='revid',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
