# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0009_auto_20170913_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.AddField(
            model_name='document',
            name='number_of_annotations',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='revid',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
