# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_auto_20170913_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=0, max_length=64, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='revid',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
