# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-13 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0011_auto_20170913_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=uuid.uuid1, max_length=64, primary_key=True, serialize=False),
        ),
    ]
